update `hex_string` fortran benchmark
JuliaLang/Microbenchmarks pull request #68
Opened 2022-06-05 18:22 UTC by oscardssmith

changes based on https://github.com/JuliaLang/Microbenchmarks/issues/67

2022-06-10 17:50 UTC, oscardssmith commented
@xecej4 any idea why this is failing the tests?

2022-06-10 18:33 UTC, acxz commented
I believe this is failing due to the newer julia version. I need to redo some of the julia benchmarks with newer julia functionality.
Particularly trying to get rid of this compat file: https://github.com/JuliaLang/Microbenchmarks/blob/master/perfutil.jl

2022-06-11 03:22 UTC, xecej4 commented
Sorry, I have no idea what the testing procedure is or what tests are run. I am not familiar with Github (other than just downloading files from it). I did compile and run prog.f90 after making my suggested changes, using several Fortran compilers on my Windows PC and on a cloud Linux server, and the program ran normally, with less time used in the parse_string tests.


  *   Mecej4
  *
From: Oscar ***@***.***>
Sent: Friday, June 10, 2022 12:50 PM
To: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Subject: Re: [JuliaLang/Microbenchmarks] update `hex_string` fortran benchmark (PR #68)


@xecej4<https://github.com/xecej4> any idea why this is failing the tests?

—
Reply to this email directly, view it on GitHub<https://github.com/JuliaLang/Microbenchmarks/pull/68#issuecomment-1152599360>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQNQ2RLCKLAOKXYBWTO6TK3VON57LANCNFSM5X5NBABA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-06-18 05:38 UTC, acxz commented
@oscardssmith sorry that it took me a while to get around to this, but if you could rebase this PR off the latest master, it should resolve the CI errors we are seeing.

@xecej4 thanks for the analysis on your local machine we should be able to confirm from the CI benchmarks as well. You can check the CI output yourself by clicking on the Details link. It will have a bunch of build/run output as well as the timings.

2022-06-18 05:39 UTC, acxz requested changes

2022-06-18 05:39 UTC, acxz commented on perf.f90
> +end do
Can we match the indentation and spacing as much as possible?

2022-06-18 13:05 UTC, acxz commented
CI passes and shows similar improvement as displayed by local results of @xecej4 

Given that the benchmark in question (parse_int) does not focus on how to write out the string in hex, this is a valid change to the benchmark and merging this in.

Thx for the contrib @xecej4 and for the help in pushing this along @oscardssmith !

2022-06-18 13:05 UTC, merged